[tool.poetry]
name = "01-дз-букреева-ольга"
version = "0.1.0"
description = ""
authors = ["Oh Olya <chanfoxx@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
